- name: Crear ubicación para binarios de usuario
  file: path={{ binary_user_path }} state=directory

- name: Descargar tarball Homemaker
  get_url: url=https://foosoft.net/projects/homemaker/dl/homemaker_linux_amd64.tar.gz dest=/tmp/

- name: Descomprimir tarball Homemaker
  unarchive: src=/tmp/homemaker_linux_amd64.tar.gz dest=/tmp copy=no

- name: Instalar Homemaker al path bin del usuario
  copy: remote_src=true src=/tmp/homemaker_linux_amd64/homemaker dest={{ binary_user_path }} mode=0775
