- name: Instalar paquetes de desarrollo
  become: true
  apt: pkg={{ pkgs }} state=installed update_cache=yes

- name: Configurar kexec-tools para manejar reinicios rápidos
  become: true
  debconf: name='kexec-tools' question='kexec-tools/load_kexec' value='true' vtype='boolean'

- name: Configurar kexec-tools para usar config de grub
  become: true
  debconf: name='kexec-tools' question='kexec-tools/use_grub_config' value='true' vtype='boolean'
