- name: Añadir repo de ubuntu-make
  become: true
  apt_repository: repo='ppa:ubuntu-desktop/ubuntu-make'

- name: Instalar paquetes de desarrollo
  become: true
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - git-core
    - postgresql-client
    - build-essential
    - tree
    - sl
    - gitg
    - ubuntu-make
    - vim
    - htop
    - atop
