- name: Agregar PPA de Webupd8 java
  become: true
  apt_repository: repo='ppa:webupd8team/java'

- name: Aceptar licencia de Oracle
  become: true
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Instalar JDK 8 de Oracle
  become: true
  apt: name=oracle-java8-installer update_cache=yes

- name: Setear oracle jdk como el java por defecto
  become: true
  alternatives: name=java path=/usr/lib/jvm/java-8-oracle/jre/bin/java

- name: Setear oracle jdk como el javac por defecto
  become: true
  alternatives: name=javac path=/usr/lib/jvm/java-8-oracle/bin/javac

- name: Instalar Maven
  become: true
  apt: name=maven state=present
