- name: Añadir repo de ubuntu-make
  become: true
  apt_repository: repo='ppa:ubuntu-desktop/ubuntu-make'

- name: Instalar PHPStorm
  shell: echo {{ umake_home }}/ide/phpstorm | umake ide phpstorm
  args:
    creates: "{{ umake_home }}/bin/jetbrains-phpstorm"
